# Generated by Django 4.2.6 on 2023-12-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_nota_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='nombre',
        ),
    ]
